name: flutter_vcarlys
description: A new Flutter project for user registration with Laravel backend.

publish_to: 'none' # Esto evita publicar el paquete accidentalmente

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Para realizar peticiones HTTP (POST, GET, etc.)
  http: ^0.13.6

  # Esto es para la conexion con verser
  flutter_dotenv: ^5.0.2

  # Dependencias para pruebas (opcional)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - .env